version: '3.4'

services:
  catalogdb:
    image: postgres
  basketdb:
    image: postgres
  distributedcache:
    image: redis
  orderdb:
    image: mcr.microsoft.com/mssql/server
  catalogapi:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/CatalogAPI/Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile

  discountgrpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: Services/Discount/DiscountGrpc/Dockerfile


volumes:
  postgres_catalog:
  postgres_basket:




